[phases.setup]
nixPkgs = ["php84", "php84Packages.composer", "nodejs_22", "nginx"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install"
]

[phases.build]
cmds = [
  "npm run build",
  "php artisan storage:link --force",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "php artisan migrate --force"
]
